name: Uptime

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'


jobs:
  run-uptime:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Download binary
        uses: actions/download-artifact@v2
        with:
          name: binary

      # - name: Check binary exists
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     workflow: build.yml
      #     repo: ${{ github.repository }}


      - name: ğŸƒ Run uptime
        run: chmod +x main && ./main
